mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'puppetlabs/apt' '3.0.0'
mod 'puppetlabs/translate' '2.0.0'
mod 'stahnma-epel'
