mod 'puppet/nginx'
mod 'puppetlabs/stdlib' , '4.16.0'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'stahnma/epel'
mod 'puppetlabs/apt' , '3.0.0'
mod 'puppetlabs/translate'
