mod 'puppet/nginx' , '0.11.0'
mod 'puppetlabs/stdlib' , '4.16.0'
mod 'puppetlabs/concat', '4.2.0'
mod 'pltraining/dockeragent'
mod 'puppetlabs/docker' ,'3.3.0' 
mod 'stahnma/epel'
mod 'puppetlabs/apt' , '3.0.0'
mod 'puppetlabs/translate'
